// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijzegsgylhiofyytkgso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqemVnc2d5bGhpb2Z5eXRrZ3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMDQ3MzcsImV4cCI6MjA1Njc4MDczN30.-cJw0taxF43BLjSZ_Yt769ml-XSmNBSQ-GorY7ed35Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);